### ISSUE TITLE
Is the menu currently outdated or is this a problem from my end

### ISSUE THREAD

**Issue by xdadova** [cazzwastaken/crashed#9]
when i inject this appears and nothing else 
![image](https://user-images.githubusercontent.com/83107663/214034971-0dca004a-699d-41f6-850a-ae8ab8cb82d6.png)

**Comment by fuso9** [comment]
he hasnt updated this repository in a year so the offsets are outdated

**Comment by cazzwastaken** [comment]
It's because I had stripped the project of its ESP during the time. I have since re-added it and updated the menu. (open with INSERT)

**Comment by cazzwastaken** [comment]
It's because I had stripped the project of its ESP during the time. I have since re-added it and updated the menu. (open with INSERT)
